[Icon Theme]
Name=Ultron-Icons
Comment=Ultron OS Icon Theme by Nexvisora Research
Inherits=breeze,hicolor
Directories=16x16/apps,16x16/devices,16x16/mimetypes,16x16/status,16x16/actions,24x24/apps,24x24/devices,24x24/mimetypes,24x24/status,24x24/actions,32x32/apps,32x32/devices,32x32/mimetypes,32x32/status,32x32/actions,48x48/apps,48x48/devices,48x48/mimetypes,48x48/status,48x48/actions,64x64/apps,64x64/devices,64x64/mimetypes,64x64/status,64x64/actions,128x128/apps,128x128/devices,128x128/mimetypes,128x128/status,128x128/actions,256x256/apps,256x256/devices,256x256/mimetypes,256x256/status,256x256/actions,scalable/apps,scalable/devices,scalable/mimetypes,scalable/status,scalable/actions

[16x16/apps]
Size=16
Context=Apps
MinSize=16
MaxSize=16
Type=Threshold

[16x16/devices]
Size=16
Context=Devices
MinSize=16
MaxSize=16
Type=Threshold

[16x16/mimetypes]
Size=16
Context=MimeTypes
MinSize=16
MaxSize=16
Type=Threshold

[16x16/status]
Size=16
Context=Status
MinSize=16
MaxSize=16
Type=Threshold

[16x16/actions]
Size=16
Context=Actions
MinSize=16
MaxSize=16
Type=Threshold

[24x24/apps]
Size=24
Context=Apps
MinSize=24
MaxSize=24
Type=Threshold

[24x24/devices]
Size=24
Context=Devices
MinSize=24
MaxSize=24
Type=Threshold

[24x24/mimetypes]
Size=24
Context=MimeTypes
MinSize=24
MaxSize=24
Type=Threshold

[24x24/status]
Size=24
Context=Status
MinSize=24
MaxSize=24
Type=Threshold

[24x24/actions]
Size=24
Context=Actions
MinSize=24
MaxSize=24
Type=Threshold

[32x32/apps]
Size=32
Context=Apps
MinSize=32
MaxSize=32
Type=Threshold

[32x32/devices]
Size=32
Context=Devices
MinSize=32
MaxSize=32
Type=Threshold

[32x32/mimetypes]
Size=32
Context=MimeTypes
MinSize=32
MaxSize=32
Type=Threshold

[32x32/status]
Size=32
Context=Status
MinSize=32
MaxSize=32
Type=Threshold

[32x32/actions]
Size=32
Context=Actions
MinSize=32
MaxSize=32
Type=Threshold

[48x48/apps]
Size=48
Context=Apps
MinSize=48
MaxSize=48
Type=Threshold

[48x48/devices]
Size=48
Context=Devices
MinSize=48
MaxSize=48
Type=Threshold

[48x48/mimetypes]
Size=48
Context=MimeTypes
MinSize=48
MaxSize=48
Type=Threshold

[48x48/status]
Size=48
Context=Status
MinSize=48
MaxSize=48
Type=Threshold

[48x48/actions]
Size=48
Context=Actions
MinSize=48
MaxSize=48
Type=Threshold

[64x64/apps]
Size=64
Context=Apps
MinSize=64
MaxSize=64
Type=Threshold

[64x64/devices]
Size=64
Context=Devices
MinSize=64
MaxSize=64
Type=Threshold

[64x64/mimetypes]
Size=64
Context=MimeTypes
MinSize=64
MaxSize=64
Type=Threshold

[64x64/status]
Size=64
Context=Status
MinSize=64
MaxSize=64
Type=Threshold

[64x64/actions]
Size=64
Context=Actions
MinSize=64
MaxSize=64
Type=Threshold

[128x128/apps]
Size=128
Context=Apps
MinSize=128
MaxSize=128
Type=Threshold

[128x128/devices]
Size=128
Context=Devices
MinSize=128
MaxSize=128
Type=Threshold

[128x128/mimetypes]
Size=128
Context=MimeTypes
MinSize=128
MaxSize=128
Type=Threshold

[128x128/status]
Size=128
Context=Status
MinSize=128
MaxSize=128
Type=Threshold

[128x128/actions]
Size=128
Context=Actions
MinSize=128
MaxSize=128
Type=Threshold

[256x256/apps]
Size=256
Context=Apps
MinSize=256
MaxSize=256
Type=Threshold

[256x256/devices]
Size=256
Context=Devices
MinSize=256
MaxSize=256
Type=Threshold

[256x256/mimetypes]
Size=256
Context=MimeTypes
MinSize=256
MaxSize=256
Type=Threshold

[256x256/status]
Size=256
Context=Status
MinSize=256
MaxSize=256
Type=Threshold

[256x256/actions]
Size=256
Context=Actions
MinSize=256
MaxSize=256
Type=Threshold

[scalable/apps]
Size=48
Context=Apps
MinSize=16
MaxSize=512
Type=Scalable

[scalable/devices]
Size=48
Context=Devices
MinSize=16
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Size=48
Context=MimeTypes
MinSize=16
MaxSize=512
Type=Scalable

[scalable/status]
Size=48
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

[scalable/actions]
Size=48
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable
